# Generated by Django 5.1.6 on 2025-03-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadro', models.CharField(max_length=255, verbose_name='Quadro')),
                ('responsavel', models.CharField(max_length=255, verbose_name='Responsavel')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('status', models.FloatField(verbose_name='Status')),
                ('data', models.DateField(verbose_name='Data entrega')),
                ('imagem', models.FileField(upload_to='imagens', verbose_name='Imagem')),
            ],
        ),
    ]
